---
id: calc
description: This is the package for the Copland tutorials.

service-points:

  Adder:
    implementor: Adder.php::Adder

  Subtractor:
    implementor: Subtractor.php::Subtractor

  Multiplier:
    implementor: Multiplier.php::Multiplier

  Divider:
    implementor: Divider.php::Divider

  Calculator:
    model: prototype
    implementor:
      class: Calculator.php::Calculator
      properties:
        adder: !!service calc.Adder
        subtractor: !!service calc.Subtractor
        divider: !!service calc.Divider
        multiplier: !!service calc.Multiplier
        memory: 0
        functions: !!configuration calc.CalculatorFunctions

configuration-points:

  CalculatorFunctions:
    type: map
