---
id: tutorial
description: This is the package for the Copland tutorial 02.

service-points:

  Adder:
    implementor: tutorial.php::Adder

  Subtractor:
    implementor: tutorial.php::Subtractor

  Multiplier:
    implementor: tutorial.php::Multiplier

  Divider:
    implementor: tutorial.php::Divider

  Calculator:
    implementor:
      class: tutorial.php::Calculator
      properties:
        adder: !!service tutorial.Adder
        subtractor: !!service tutorial.Subtractor
        divider: !!service tutorial.Divider
        multiplier: !!service tutorial.Multiplier
