---
id: calc.functions
description: This is the package for the Copland tutorials.

service-points:

  Sine:
    implementor: functions/Sine.php::Sine


contributions:

  calc.CalculatorFunctions:
    sin: !!service calc.functions.Sine
